    
name: 'Se7e environment'
description: 'Install se7e environment'
inputs:
  token:
    description: 'A Github PAT'
    required: true
runs:
  using: "composite"
  steps:
  - name: Set up Python 3.10
    uses: actions/setup-python@v3
    with:
      python-version: "3.10"
  - name: Install pyobject
    run: | 
      sudo apt-get install -y gir1.2-gtk-3.0 libgtk-3-dev pkg-config libcairo2-dev gcc python3-dev libgirepository1.0-dev
      pip install PyGObject
      pip install -U git+https://github.com/welitonfreitas/nose-py3.git@master
    shell: bash
  - name: download se7e
    uses: actions/checkout@v3
    with:
      repository: setor7soft/se7e
      submodules: 'true'
      path: ../_se7e
      token: ${{ inputs.token }}
  - name: download kiwi
    uses: actions/checkout@v3
    with:
      repository: setor7soft/kiwi
      submodules: 'true'
      path: ../_kiwi
      token: ${{ inputs.token }}
  - name: download stoqdrivers
    uses: actions/checkout@v3
    with:
      repository: setor7soft/stoqdrive
      submodules: 'true'
      path: ../_stoqdrive
      token: ${{ inputs.token }}
  - name: Install se7e dependencies
    run: |
      cd ${{github.action_path}}/_se7e
      python -m pip install --upgrade pip
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    shell: bash
  - name: Install kiwi dependencies
    run: |
      cd ../_kiwi
      python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    shell: bash
  - name: Install stoqdrive dependencies
    run: |
      cd ../_stoqdrive
      python -m pip install --upgrade pip
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    shell: bash
  - name: ls repos
    run: |
      ls ../
      ls ./
      ls /
    shell: bash
  - name: set PYTHONPATH
    run: |
      echo "PYTHONPATH=../_se7e:../_kiwi:../_stoqdrive" >> $GITHUB_ENV
    shell: bash
